name: Java CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Build
        run: ./mvnw clean compile
      - name: Test
        run: ./mvnw test
      - name: Package
        run: ./mvnw package -DskipTests